config/routes.rb
Rails.application.routes.draw do
  root to: 'wines#index'
  resources :wines
  get 'wine_details', to: 'wines#wine_details'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wine.rb
class Wine < ApplicationRecord
  before_create :set_sku

  def set_sku
    write_attribute(:sku, "#{producer.capitalize}, #{cuvee.capitalize}, #{appellation.capitalize} #{vintage} (#{grape_variety.capitalize})")
    puts sku
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all
  end

  def wine_details
    @wines = Wine.all
    @detail = params[:wine_details]
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:sku, :supplier, :producer, :cuvee, :grape_variety, :style, :vintage, :btl_size, :btls_case, :cost_case, :appellation, :app_ii, :region, :country, :classification, :abv, :other, :blend, :blend_grapes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>IMS Feature Demo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="IMS Feature Demo Page">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= turbo_include_tags %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
</head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/wines/_details_table.html.erb
<div class="table-responsive">
  <table class="table table-hover ">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Country</th>
      <th scope="col">Style</th>
      <th scope="col">Btl_Size</th>
      <th scope="col">Grape</th>
      <th scope="col">Vintage</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% wines.each do |wine| %>
      <tr scope="row">
        <td style="font-weight: bold;"><%= wine.sku %></td>
        <td><%= wine.country %></td>
        <td><%= wine.style %></td>
        <td><%= wine.btl_size %></td>
        <td><%= wine.grape_variety %></td>
        <td><%= wine.vintage %></td>
        <td>
          <%= link_to 'View', wine,
                      class: '
                                text-indigo-600
                                hover:text-indigo-800'%>

        <td>
          <%= link_to 'Edit', edit_wine_path(wine),
                      class: '
                                text-green-600
                                hover:text-green-800'%>

        <td>
          <%= link_to 'Delete', wine, method: :delete, data: { confirm: 'Are you sure?' },
                      class: '
                                text-red-600
                                hover:text-red-800'%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
        <% wine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if wine.sku.present? %>
  <div class="field">
    <%= form.label :sku %>
    <%= form.text_field :sku, class: 'form-control' %>
  </div>
  <% end %>
  <div class="field">
    <%= form.label :supplier %>
    <%= form.text_field :supplier, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :producer %>
    <%= form.text_field :producer, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :cuvee %>
    <%= form.text_field :cuvee, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :grape_variety %>
    <%= form.text_field :grape_variety, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :vintage %>
    <%= form.text_field :vintage, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :btl_size %>
    <%= form.number_field :btl_size, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :btls_case %>
    <%= form.number_field :btls_case, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :cost_case %>
    <%= form.text_field :cost_case, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :appellation %>
    <%= form.text_field :appellation, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :app_ii %>
    <%= form.text_field :app_ii, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :classification %>
    <%= form.text_field :classification, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :abv %>
    <%= form.text_field :abv, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :other %>
    <%= form.text_field :other, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :blend %>
    <%= form.check_box :blend %>
  </div>

  <div class="field">
    <%= form.label :blend_grapes %>
    <%= form.text_field :blend_grapes, class: 'form-control' %>
  </div>
<br/>
  <div class="actions">
    <%= form.submit 'submit', class: 'btn btn btn-secondary' %>
  </div>
<% end %>

app/views/wines/_links.html.erb
<div class="text-center" style="padding-bottom: 10px">
  <style>
    a {
        margins:0;
    }
  </style>
  <%= link_to 'Wine Details', wine_details_path(wine_details: 'details'),
              class: '
              border-t
              border-l
              border-r
              hover:bg-gray-300
              text-gray-800
              hover:text-gray-900
              hover:no-underline
              my-0 py-2 px-4 mx-0' %>
  <%= link_to 'Supplier Details', wine_details_path(wine_details: 'supplier'),
              class: '
              border-t
              border-l
              border-r
              hover:bg-gray-300
              text-gray-800
              hover:text-gray-900
              hover:no-underline
              my-0 py-2 px-4 mx-0' %>
</div>

app/views/wines/_suppliers_table.html.erb
<div class="table-responsive">
  <table class="table table-hover ">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Supplier</th>
      <th scope="col">Producer</th>
      <th scope="col">Btl_Size</th>
      <th scope="col">Btls/Case</th>
      <th scope="col">Cost/Case</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% wines.each do |wine| %>
      <tr scope="row">
        <td style="font-weight: bold;"><%= wine.sku %></td>
        <td><%= wine.supplier %></td>
        <td><%= wine.producer %></td>
        <td><%= wine.btl_size %></td>
        <td><%= wine.btls_case %></td>
        <td><%= wine.cost_case %></td>
        <td>
          <%= link_to 'View', wine,
                        class: '
                                text-indigo-600
                                hover:text-indigo-800'%>

        <td>
          <%= link_to 'Edit', edit_wine_path(wine),
                        class: '
                                text-green-800
                                hover:text-green-900'%>

        <td>
          <%= link_to 'Delete', wine, method: :delete, data: { confirm: 'Are you sure?' },
                        class: '
                                text-red-600
                                hover:text-red-800'%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= turbo_frame_tag 'wines' do %>
  <div class="w-full">
    <%= render 'form', wine: @wine %>
  </div>
  <%= link_to 'Show', @wine %> |
  <%= link_to 'Back', wines_path %>
<% end %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<div class="max-w-max min-w-min mx-auto flex p-6 bg-white rounded-lg shadow-xl overflow-auto">
    <%= turbo_frame_tag 'wines' do %>
      <%= render partial: 'wines/links' %>

      <%= render partial: 'wines/details_table', locals: {wines: @wines} %>
    <% end %>
</div>

<br>

<%= link_to 'New Wine', new_wine_path, class: 'btn btn-sm btn-secondary' %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>
<%= turbo_frame_tag 'wines' do %>

  <p>
    <strong>Name:</strong>
    <%= @wine.sku %>
  </p>


  <p>
    <strong>Supplier:</strong>
    <%= @wine.supplier %>
  </p>

  <p>
    <strong>Producer:</strong>
    <%= @wine.producer %>
  </p>

  <p>
    <strong>Cuvee:</strong>
    <%= @wine.cuvee %>
  </p>

  <p>
    <strong>Grape variety:</strong>
    <%= @wine.grape_variety %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= @wine.style %>
  </p>

  <p>
    <strong>Vintage:</strong>
    <%= @wine.vintage %>
  </p>

  <p>
    <strong>Btl size:</strong>
    <%= @wine.btl_size %>
  </p>

  <p>
    <strong>Btls case:</strong>
    <%= @wine.btls_case %>
  </p>

  <p>
    <strong>Cost case:</strong>
    <%= @wine.cost_case %>
  </p>

  <p>
    <strong>Appellation:</strong>
    <%= @wine.appellation %>
  </p>

  <p>
    <strong>App ii:</strong>
    <%= @wine.app_ii %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= @wine.region %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= @wine.country %>
  </p>

  <p>
    <strong>Classification:</strong>
    <%= @wine.classification %>
  </p>

  <p>
    <strong>Abv:</strong>
    <%= @wine.abv %>
  </p>

  <p>
    <strong>Other:</strong>
    <%= @wine.other %>
  </p>

  <p>
    <strong>Blend:</strong>
    <%= @wine.blend %>
  </p>

  <p>
    <strong>Blend grapes:</strong>
    <%= @wine.blend_grapes %>
  </p>
  </div>
  </div>


  <%= link_to 'Edit', edit_wine_path(@wine) %> |
  <%= link_to 'Back', wines_path %>
<% end %>

app/views/wines/wine_details.html.erb
<%= turbo_frame_tag 'wines' do %>
  <%= render partial: 'wines/links' %>

  <% if @detail == 'details' %>
    <%= render partial: 'wines/details_table', locals: {wines: @wines} %>
  <% else %>
    <%= render partial: 'wines/suppliers_table', locals: {wines: @wines} %>
  <% end %>
<% end %>